### ISSUE TITLE
kairosDB V1.1.1 | Last Aggregator Issue

### ISSUE THREAD

**Issue by prerak1992** [kairosdb/kairosdb#442]
I posted the following datapoints 
````
[{"name": "testing.user.99876d21-2a57-11e7-b529-0acad1ee5072.logins","datapoints": [[1520414683250, 1], [1520420264982, 1], [1520421504226, 1]],"tags": { "provision-type": "basic" }}]
````

When I execute the below query body
````
{"metrics":[{"tags":{},"name":"testing.user.99876d21-2a57-11e7-b529-0acad1ee5072.logins","aggregators":[{"name":"last","align_sampling":true,"sampling":{"value":"1","unit":"days"}}]}],"cache_time":0, "start_absolute":0 }
````

I am expecting [1520421504226, 1] as the response, but I am getting the below response
````
{"queries":[{"sample_size":3,"results":[{"name":"testing.user.99876d21-2a57-11e7-b529-0acad1ee5072.logins","group_by":[{"name":"type","type":"number"}],"tags":{"provision-type":["basic"]},"values":[[1520414683250,1]]}]}]}
````

**Comment by prerak1992** [comment]
I use datastax Cassandra 2.2.6 to store the data.
When I remove the aggregators, I am able to get all three data points, confirming that they are properly saved in KairosDB.

**Comment by brianhks** [comment]
fixed in #297

**Comment by prerak1992** [comment]
@brianhks - In #297, timestamp is wrong, but the value is correct.
In our case, both value and timestamp are wrong.

Can you please confirm that the issue is still related to #297 and can be fixed by upgrading KairosDB version.

**Comment by brianhks** [comment]
In your example the values are all 1 so it is hard to tell if you got the right value or not.  I tested your example on 1.1.3 but used the values 1,2,3 and I got back the last data point.
